- name: Deploy HTML to Server
  hosts: all
  become: yes

  tasks:
  
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Copy HTML
      copy:
        src: ../index.html
        dest: /var/www/html/index.html

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
